# Generated by Django 4.0.3 on 2022-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_players_delete_item_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('itemLink', models.CharField(max_length=200)),
                ('itemPhoto', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
